import { authOptions } from "@/lib/auth";
import type { Metadata } from "next";
import { getServerSession } from "next-auth";
import { Geist, Geist_Mono, JetBrains_Mono, Public_Sans, Roboto } from "next/font/google";
import "./globals.css";
import { Providers } from "./provider";
import LoginPage from "./login/page";

const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' });
const publicSans = Public_Sans({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const jetBrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Karman",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);

  return (
    <html className={roboto.variable} data-scroll-behavior="smooth">
      <body
        className={`${geistSans.variable} ${jetBrainsMono.variable} antialiased`}>

        <Providers session={session}>
          {children}
          {/* {session.user==='authenticated' ? children : <LoginPage/>} */}
 
        </Providers>

      </body>
    </html>
  );
}
